version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=https://zsplqmaaoqrpyzdsykkm.supabase.co
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcGxxbWFhb3FycHl6ZHN5a2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NDEwOTksImV4cCI6MjA1MDQxNzA5OX0.20XfvooSKx8mGMc6bF7M8KWNfrTUgX-ieeGwBaX_6bY
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=https://zsplqmaaoqrpyzdsykkm.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcGxxbWFhb3FycHl6ZHN5a2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NDEwOTksImV4cCI6MjA1MDQxNzA5OX0.20XfvooSKx8mGMc6bF7M8KWNfrTUgX-ieeGwBaX_6bY
    command: npm run dev
    tty: true
    stdin_open: true
